spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    driver-class-name: org.postgresql.Driver
    username: demo_user
    password: demo_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/demo
          jwk-set-uri: http://keycloak:8180/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8180/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: demo-rest-client
            client-secret: ZORoJcMtwn7bEPoH4FYeN2YN78LkZpGS
            authorization-grant-type: authorization_code
            scope: openid

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.cloud.gateway: DEBUG

springdoc:
  api-docs:
    path: /api-docs

application:
  services:
    payment:
      url: http://localhost:8080/api/payment
    inventory:
      url: http://localhost:8080/api/inventory
    s3:
      endpoint: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadminpassword
      region: us-east-1