version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres-keycloak:5432/keycloak"
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_REALM_NAME: demo
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro

  postgres-keycloak:
    image: postgres:15.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata_keycloak:/var/lib/postgresql/data

  postgres-demo:
    image: postgres:15.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata_demo:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: [
      "/bin/sh",
      "-c",
      "until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword) do sleep 1; done; /usr/bin/mc mb myminio/demobucket"
    ]

volumes:
  local_pgdata_keycloak:
  local_pgdata_demo:
  pgadmin-data:
  minio-data: